-- MySQL Script generated by MySQL Workbench
-- Thu Jun 11 19:25:23 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema strong_beton
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema strong_beton
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `strong_beton` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
-- -----------------------------------------------------
-- Table `strong_beton`.`additional_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `strong_beton`.`additional_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `cm` INT NULL DEFAULT NULL,
  `born_date` DATE NULL DEFAULT NULL,
  `gender` TINYINT(1) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 73
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `strong_beton`.`clan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `strong_beton`.`clan` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(65) NOT NULL,
  `description` VARCHAR(1024) NOT NULL,
  `logo_url` VARCHAR(255) NULL DEFAULT NULL,
  `total_xp` INT NOT NULL DEFAULT '0',
  `clan_level` INT NOT NULL,
  `current_league` ENUM('UNRANKED', 'BRONZE', 'SILVER', 'GOLD', 'DIAMOND') NULL DEFAULT NULL,
  `is_invite_only` TINYINT NULL DEFAULT '0',
  `clan_points` INT NULL DEFAULT '0',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `logo_from_photo_foreign_idx` (`logo_url` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `strong_beton`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `strong_beton`.`role` (
  `id_role` INT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_role`),
  UNIQUE INDEX `role_name_UNIQUE` (`role_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `strong_beton`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `strong_beton`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid_user` BINARY(16) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `additional_info_id` INT NULL DEFAULT NULL,
  `role_id` INT NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `uuid_user_UNIQUE` (`uuid_user` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `additional_info_id_UNIQUE` (`additional_info_id` ASC) VISIBLE,
  INDEX `user_role_fk` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_additional_info`
    FOREIGN KEY (`additional_info_id`)
    REFERENCES `strong_beton`.`additional_info` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `user_role_fk`
    FOREIGN KEY (`role_id`)
    REFERENCES `strong_beton`.`role` (`id_role`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `strong_beton`.`clan_member_contribution`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `strong_beton`.`clan_member_contribution` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `clan_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `points` INT NOT NULL,
  `date` TIMESTAMP NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_clan_contribution` (`clan_id` ASC) VISIBLE,
  INDEX `fk_clan_member_contribution` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_clan_contribution`
    FOREIGN KEY (`clan_id`)
    REFERENCES `strong_beton`.`clan` (`id`),
  CONSTRAINT `fk_clan_member_contribution`
    FOREIGN KEY (`user_id`)
    REFERENCES `strong_beton`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `strong_beton`.`clan_members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `strong_beton`.`clan_members` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `clan_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `clan_role` ENUM('LEADER', 'OFFICER', 'STRENGTH_SPECIALIST', 'VOLUME_SPECIALIST', 'CONSISTENCY_SPECIALIST', 'MEMBER', 'PENDING') NULL DEFAULT NULL,
  `joined_at` TIMESTAMP NOT NULL,
  `points` INT NULL DEFAULT '0',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_clan_members_user_clan` (`user_id` ASC, `clan_id` ASC) VISIBLE,
  INDEX `fk_clan` (`clan_id` ASC) VISIBLE,
  CONSTRAINT `fk_clan`
    FOREIGN KEY (`clan_id`)
    REFERENCES `strong_beton`.`clan` (`id`),
  CONSTRAINT `fk_clan_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `strong_beton`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `strong_beton`.`clan_points`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `strong_beton`.`clan_points` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `clan_id` INT NOT NULL,
  `clan_points` INT NOT NULL,
  `date` TIMESTAMP NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_clan_id` (`clan_id` ASC) VISIBLE,
  CONSTRAINT `fk_clan_id`
    FOREIGN KEY (`clan_id`)
    REFERENCES `strong_beton`.`clan` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `strong_beton`.`coach`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `strong_beton`.`coach` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_coach_user` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_coach_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `strong_beton`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `strong_beton`.`client_coach`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `strong_beton`.`client_coach` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `coach_id` INT NOT NULL,
  `client_id` INT NOT NULL,
  `status` TINYINT NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_client_coach_coach` (`coach_id` ASC) VISIBLE,
  INDEX `fk_client_coach_client` (`client_id` ASC) VISIBLE,
  CONSTRAINT `fk_client_coach_client`
    FOREIGN KEY (`client_id`)
    REFERENCES `strong_beton`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_client_coach_coach`
    FOREIGN KEY (`coach_id`)
    REFERENCES `strong_beton`.`coach` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `strong_beton`.`coach_rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `strong_beton`.`coach_rating` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `coach_id` INT NULL DEFAULT NULL,
  `comment` VARCHAR(255) NULL DEFAULT NULL,
  `rating` DECIMAL(3,2) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_coach_rating_coach` (`coach_id` ASC) VISIBLE,
  INDEX `fk_coach_rating_user` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_coach_rating_coach`
    FOREIGN KEY (`coach_id`)
    REFERENCES `strong_beton`.`coach` (`id`),
  CONSTRAINT `fk_coach_rating_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `strong_beton`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `strong_beton`.`muscle_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `strong_beton`.`muscle_group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `muscle_group_name` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `muscle_group_name_UNIQUE` (`muscle_group_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 151
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `strong_beton`.`exercise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `strong_beton`.`exercise` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `muscle_group_id` INT NULL DEFAULT NULL,
  `difficulty_type` ENUM('COMPOUND', 'SECONDARY', 'ISOLATION') NOT NULL DEFAULT 'SECONDARY',
  `equipment_type` ENUM('BARBELL', 'DUMBBELL', 'MACHINE', 'CABLE', 'BODYWEIGHT', 'OTHER') NOT NULL DEFAULT 'OTHER',
  `active` TINYINT(1) NOT NULL DEFAULT '1',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_exercise_muscle_group` (`muscle_group_id` ASC) VISIBLE,
  CONSTRAINT `fk_exercise_muscle_group`
    FOREIGN KEY (`muscle_group_id`)
    REFERENCES `strong_beton`.`muscle_group` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 120
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `strong_beton`.`feed_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `strong_beton`.`feed_post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `content` VARCHAR(500) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `type` ENUM('WORKOUT', 'ACHIEVEMENT', 'TEXT') NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_user` (`user_id` ASC) VISIBLE,
  INDEX `idx_feed_post_created_at` (`created_at` ASC) VISIBLE,
  CONSTRAINT `fk_post_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `strong_beton`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `strong_beton`.`feed_post_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `strong_beton`.`feed_post_comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `post_id` INT NOT NULL,
  `content` VARCHAR(500) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_comment_user` (`user_id` ASC) VISIBLE,
  INDEX `idx_feed_post_comment_post_created_at` (`post_id` ASC, `created_at` ASC) VISIBLE,
  CONSTRAINT `fk_post_comment_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `strong_beton`.`user` (`id`),
  CONSTRAINT `fk_post_feed_post`
    FOREIGN KEY (`post_id`)
    REFERENCES `strong_beton`.`feed_post` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `strong_beton`.`feed_post_like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `strong_beton`.`feed_post_like` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `post_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_feed_post_like_user_post` (`user_id` ASC, `post_id` ASC) VISIBLE,
  INDEX `fk_post_post_likes` (`post_id` ASC) VISIBLE,
  CONSTRAINT `fk_post_post_likes`
    FOREIGN KEY (`post_id`)
    REFERENCES `strong_beton`.`feed_post` (`id`),
  CONSTRAINT `fk_user_post_likes`
    FOREIGN KEY (`user_id`)
    REFERENCES `strong_beton`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `strong_beton`.`friendship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `strong_beton`.`friendship` (
  `id_friendship` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `friend_id` INT NOT NULL,
  `status` ENUM('PENDING', 'NOTHING', 'ACCEPTED', 'RESPONSE') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id_friendship`),
  INDEX `fk_friendship_one_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_friendship_two_idx` (`friend_id` ASC) VISIBLE,
  CONSTRAINT `fk_friendship_one`
    FOREIGN KEY (`user_id`)
    REFERENCES `strong_beton`.`user` (`id`),
  CONSTRAINT `fk_friendship_two`
    FOREIGN KEY (`friend_id`)
    REFERENCES `strong_beton`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 62
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `strong_beton`.`injuries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `strong_beton`.`injuries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `muscle_group` INT NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_injuries_user_uuid` (`user_id` ASC) VISIBLE,
  INDEX `fk_injuries_muscle_group` (`muscle_group` ASC) VISIBLE,
  CONSTRAINT `fk_injuries_muscle_group`
    FOREIGN KEY (`muscle_group`)
    REFERENCES `strong_beton`.`muscle_group` (`id`),
  CONSTRAINT `fk_injuries_user_uuid`
    FOREIGN KEY (`user_id`)
    REFERENCES `strong_beton`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `strong_beton`.`kg_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `strong_beton`.`kg_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `kg` DECIMAL(7,2) NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `logged_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_user_kg_idx` (`user_id` ASC) VISIBLE,
  INDEX `idx_kg_log_user_logged_at` (`user_id` ASC, `logged_at` ASC) VISIBLE,
  CONSTRAINT `fk_user_kg`
    FOREIGN KEY (`user_id`)
    REFERENCES `strong_beton`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 72
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `strong_beton`.`notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `strong_beton`.`notification` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `sender_id` INT NULL DEFAULT NULL,
  `clan_id` INT NULL DEFAULT NULL,
  `type` ENUM('CLAN_INVITE', 'CLAN_INVITE_ACCEPTED', 'CLAN_INVITE_DECLINED', 'CLAN_KICKED', 'CLAN_PROMOTED', 'CLAN_DEMOTED', 'CLAN_LEADERSHIP_TRANSFERRED', 'FRIEND_REQUEST', 'FRIEND_ACCEPTED') NOT NULL,
  `is_read` TINYINT(1) NOT NULL DEFAULT '0',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_notification_sender` (`sender_id` ASC) VISIBLE,
  INDEX `fk_notification_clan` (`clan_id` ASC) VISIBLE,
  INDEX `idx_notification_user_read_created` (`user_id` ASC, `is_read` ASC, `created_at` ASC) VISIBLE,
  CONSTRAINT `fk_notification_clan`
    FOREIGN KEY (`clan_id`)
    REFERENCES `strong_beton`.`clan` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_notification_sender`
    FOREIGN KEY (`sender_id`)
    REFERENCES `strong_beton`.`user` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `fk_notification_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `strong_beton`.`user` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `strong_beton`.`photos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `strong_beton`.`photos` (
  `uuid_photo` BINARY(16) NOT NULL,
  `user_id` INT NOT NULL,
  `photo_url` VARCHAR(2048) NOT NULL,
  `photo_type` ENUM('PROFILE', 'CERTIFICATE', 'OTHER') NULL DEFAULT 'OTHER',
  `is_active` TINYINT(1) NULL DEFAULT '1',
  `uploaded_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `description` VARCHAR(500) NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`uuid_photo`),
  INDEX `user_uuid` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_photos_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `strong_beton`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `strong_beton`.`workout_template`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `strong_beton`.`workout_template` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `workout_name` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 122
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `strong_beton`.`workout`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `strong_beton`.`workout` (
  `uuid_workout` BINARY(16) NOT NULL,
  `user_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `workout_template_id` INT NOT NULL,
  `coach_id` INT NULL DEFAULT NULL,
  `status` ENUM('DRAFT', 'FINISHED') NOT NULL DEFAULT 'DRAFT',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`uuid_workout`),
  INDEX `workout_user_fk` (`user_id` ASC) VISIBLE,
  INDEX `workout_template_id` (`workout_template_id` ASC) VISIBLE,
  INDEX `fk_workout_coach` (`coach_id` ASC) VISIBLE,
  INDEX `idx_workout_user_status_date` (`user_id` ASC, `status` ASC, `date` ASC) VISIBLE,
  CONSTRAINT `fk_workout_coach`
    FOREIGN KEY (`coach_id`)
    REFERENCES `strong_beton`.`coach` (`id`),
  CONSTRAINT `fk_workout_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `strong_beton`.`user` (`id`),
  CONSTRAINT `workout_ibfk_1`
    FOREIGN KEY (`workout_template_id`)
    REFERENCES `strong_beton`.`workout_template` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `strong_beton`.`workout_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `strong_beton`.`workout_details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `workout_uuid` BINARY(16) NOT NULL,
  `exercise_id` INT NOT NULL,
  `muscle_group_id` INT NOT NULL,
  `volume` DOUBLE NULL DEFAULT NULL,
  `estimated_1rm` DOUBLE NULL DEFAULT NULL,
  `exercise_points` DOUBLE NULL DEFAULT NULL,
  `is_suspicious` TINYINT(1) NOT NULL DEFAULT '0',
  `anomaly_score` DOUBLE NULL DEFAULT NULL,
  `anomaly_reason` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_workout_details_workout_exercise` (`workout_uuid` ASC, `exercise_id` ASC) VISIBLE,
  INDEX `workout_details_workout_fk` (`workout_uuid` ASC) VISIBLE,
  INDEX `workout_details_exercise_idx` (`exercise_id` ASC) VISIBLE,
  INDEX `fk_workoutDetails_muscleGroup` (`muscle_group_id` ASC) VISIBLE,
  CONSTRAINT `fk_workoutDetails_exercise`
    FOREIGN KEY (`exercise_id`)
    REFERENCES `strong_beton`.`exercise` (`id`),
  CONSTRAINT `fk_workoutDetails_muscleGroup`
    FOREIGN KEY (`muscle_group_id`)
    REFERENCES `strong_beton`.`muscle_group` (`id`),
  CONSTRAINT `workout_details_workout_fk`
    FOREIGN KEY (`workout_uuid`)
    REFERENCES `strong_beton`.`workout` (`uuid_workout`))
ENGINE = InnoDB
AUTO_INCREMENT = 192
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `strong_beton`.`sets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `strong_beton`.`sets` (
  `id_sets` INT NOT NULL AUTO_INCREMENT,
  `reps` INT NOT NULL,
  `kg` DECIMAL(10,2) NOT NULL,
  `set_number` INT NOT NULL,
  `workout_details_id` INT NOT NULL,
  `estimated_1rm` DOUBLE NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id_sets`),
  UNIQUE INDEX `ux_sets_workout_details_set_number` (`workout_details_id` ASC, `set_number` ASC) VISIBLE,
  UNIQUE INDEX `uq_sets_workout_details_set_number` (`workout_details_id` ASC, `set_number` ASC) VISIBLE,
  INDEX `stats_workout_details` (`workout_details_id` ASC) VISIBLE,
  INDEX `idx_sets_workout_details_id` (`workout_details_id` ASC) VISIBLE,
  CONSTRAINT `stats_workout_details`
    FOREIGN KEY (`workout_details_id`)
    REFERENCES `strong_beton`.`workout_details` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 184
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

