spring.application.name=strongBeton
spring.datasource.url = jdbc:mysql://localhost:3306/strong_beton
spring.datasource.username = root
spring.datasource.password = root123


spring.main.banner-mode=off
logging.level.root=warn
server.port=8081


logging.level.org.springframework.security=DEBUG

security.jwt.secret-key=39f27faa30598b17b1006fbdfa05578add57ea39ae7dec0b166c49f0cf0775c9
# 1h in millisecond
security.jwt.expiration-time=3600000
cloudinary.cloud_name=dgaepaq1z
cloudinary.api_key=157498771644785
cloudinary.api_secret=wVxm2K5qtuF2XHp3P2sOdw0kUI8
